# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e4996fd966b8df3fa2cd839fcca9dd0ecc185cf76017d0fd3e795c1827990279fdccec46ffc3cf60ef035d716297c452f903b657c33c91001ed9d377eb7069d

test:
  secret_key_base: b9e27437a42cc1f7f3d5f5c96d2f5e0189ce54e94c18a3492643816734d017fd7a6b9f10329d89574c08876df8913540d50ecd31bcb231d4f14787eb58abd6d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
